### ISSUE TITLE
Ausência de logotipo

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#1]
**Localização:** Topo superior esquerdo
**Princípio violado:** Visibilidade; navegabilidade
**Sugestão:** Colocar logotipo ao lado do menu superior

![image](https://user-images.githubusercontent.com/3816749/27152643-d8e27214-5124-11e7-966f-775d4334c712.png)

**Comment by henriqueap** [comment]
Alterado, está Ok?
