### ISSUE TITLE
Itens do menu em ordem não habitual

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#11]
**Local:** Menu superior
**Princípios violados:** Navegabilidade
**Sugestão:** Ordenar itens do menu por ordem de mais acessados

![image](https://user-images.githubusercontent.com/3816749/27153198-dbe7d79a-5126-11e7-84b9-78de93dc3177.png)

**Comment by henriqueap** [comment]
Alterado, está Ok?
