### ISSUE TITLE
Imagem na página de História não se adéqua a telas menores

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#17]
**Local:** Página História
**Princípios violados:** Alinhamento; responsividade
**Sugestão:** Implementar responsividade nesta imagem

![image](https://user-images.githubusercontent.com/3816749/27153567-59b31134-5128-11e7-88e7-2e0c70face81.png)

**Comment by henriqueap** [comment]
Alterado, está Ok?
