### ISSUE TITLE
Imagem na página de História não condiz com o texto apresentado abaixo

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#21]
**Local:** Página História
**Princípios violados:** Consistência
**Sugestão:** Mudar a imagem

![image](https://user-images.githubusercontent.com/3816749/27153759-0db1478c-5129-11e7-9069-175162c67602.png)

**Comment by henriqueap** [comment]
Já tem a imagem nova, sem os números? A responsividade está ok.
