### ISSUE TITLE
Pop-up que pergunta o nome do usuário não é adequado

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#25]
**Local:** Página Início
**Princípios violados:** Feedback adequado
**Sugestão:** Retirar pop-up

![image](https://user-images.githubusercontent.com/3816749/27153875-7214b7cc-5129-11e7-9220-4c379028cbda.png)

**Comment by henriqueap** [comment]
Alterado pela LadyBlonde, está Ok?
