### ISSUE TITLE
Menu não indica a página atual

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#4]
**Local:** Menu superior
**Princípios violados:** Visibilidade; navegabilidade; feedback adequado
**Sugestão:** Colocar o item do menu ao qual a página atual pertence como ativo

![image](https://user-images.githubusercontent.com/3816749/27152938-ff243e84-5125-11e7-89ef-8df59708c9af.png)

**Comment by henriqueap** [comment]
Alterado, está Ok?
