### ISSUE TITLE
Ícones nos itens do menu

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#6]
**Local:** Menu superior
**Princípios violados:** Navegabilidade; metáfora; consistência
**Sugestão:** Inserir ícones

![image](https://user-images.githubusercontent.com/3816749/27153017-3e907aba-5126-11e7-9826-650159b8b7fc.png)

**Comment by henriqueap** [comment]
Pus o logo com link e o banner agora é link também. Está ok?

**Comment by yvesmariano** [comment]
Falta os ícones nos itens do menu

**Comment by yvesmariano** [comment]
Deixa pra lá
