### ISSUE TITLE
Ausência de títulos nas páginas

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#8]
**Local:** Parte superior de todas as páginas
**Princípios violados:** Navegabilidade
**Sugestão:** Inserir títulos em todas as páginas

![image](https://user-images.githubusercontent.com/3816749/27153198-dbe7d79a-5126-11e7-84b9-78de93dc3177.png)

**Comment by henriqueap** [comment]
Alterado, está Ok?
