### ISSUE TITLE
Item do menu chamado "X-men" não condiz com a página

### ISSUE THREAD

**Issue by yvesmariano** [LadyBlonde/xmen#9]
**Local:** Menu superior
**Princípios violados:** Consistência
**Sugestão:** Alterar para "Fundadores"

![image](https://user-images.githubusercontent.com/3816749/27153198-dbe7d79a-5126-11e7-84b9-78de93dc3177.png)

**Comment by henriqueap** [comment]
Alterado, está Ok?
